name: Docker Build
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: build
        run: |
          docker login docker.pkg.github.com -u mokhan -p ${{ secrets.GITHUB_TOKEN }}
          docker pull docker.pkg.github.com/mokhan/mst:latest || true
          docker build --cache-from docker.pkg.github.com/mokhan/mst:latest -t docker.pkg.github.com/mokhan/mst:latest .
          docker push docker.pkg.github.com/mokhan/mst:latest
